# Generated by Django 6.0.4 on 2026-04-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('scheme_id', models.IntegerField()),
                ('farmer_name', models.CharField(max_length=255)),
                ('farmer_phone', models.CharField(max_length=20)),
                ('farmer_aadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=20)),
                ('application_data', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_application',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total_schemes', models.IntegerField(default=0)),
                ('trending_schemes', models.JSONField(default=list)),
                ('total_farmers_benefited', models.IntegerField(default=0)),
                ('recent_applications', models.JSONField(default=list)),
                ('featured_offers', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_dashboard',
            },
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('scheme_id', models.IntegerField()),
                ('criteria', models.JSONField(default=dict)),
                ('min_land_size', models.FloatField(blank=True, null=True)),
                ('max_land_size', models.FloatField(blank=True, null=True)),
                ('max_annual_income', models.IntegerField(blank=True, null=True)),
                ('eligible_states', models.JSONField(default=list)),
                ('eligible_genders', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_eligibility',
            },
        ),
        migrations.CreateModel(
            name='LoanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('loan_type', models.CharField(choices=[('AGRICULTURAL', 'Agricultural Loan'), ('KISAN_CREDIT', 'Kisan Credit Card'), ('TRACTOR', 'Tractor Loan'), ('EQUIPMENT', 'Equipment Loan')], max_length=20)),
                ('annual_interest_rate', models.FloatField()),
                ('tenure_months', models.IntegerField()),
                ('processing_fee_percent', models.FloatField()),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('prepayment_policy', models.TextField()),
                ('documents_required', models.JSONField(default=list)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_loan_option',
            },
        ),
        migrations.CreateModel(
            name='MandiPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandi_id', models.IntegerField(db_index=True, unique=True)),
                ('mandi_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=255)),
                ('crops', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_mandi_price',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(default='🌾', max_length=10)),
                ('details', models.TextField()),
                ('government_level', models.CharField(choices=[('CENTRAL', 'Central Government'), ('STATE', 'State Government'), ('CENTRAL_STATE', 'Central + State Government')], max_length=20)),
                ('states', models.JSONField(default=list)),
                ('descriptions', models.JSONField(default=dict)),
                ('benefits', models.JSONField(default=dict)),
                ('how_to_apply', models.JSONField(default=dict)),
                ('documents_required', models.JSONField(default=dict)),
                ('eligibility', models.JSONField(default=dict)),
                ('authority', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheme',
                'verbose_name_plural': 'Schemes',
                'db_table': 'data_scheme',
            },
        ),
    ]
