# Generated by Django 6.0.4 on 2026-04-26 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('farmer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('farmer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('messages', models.JSONField(default=list)),
                ('context', models.JSONField(default=dict)),
                ('final_response', models.JSONField(blank=True, null=True)),
                ('outcomes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'voice_agent_conversation',
            },
        ),
        migrations.CreateModel(
            name='VoiceAgentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('message', models.TextField()),
                ('speak', models.TextField()),
                ('redirect_page', models.CharField(blank=True, max_length=50, null=True)),
                ('result_items', models.JSONField(default=list)),
                ('language', models.CharField(max_length=10)),
                ('confidence', models.FloatField(default=0.9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='voice_agent.voiceconversation')),
            ],
            options={
                'db_table': 'voice_agent_response',
            },
        ),
        migrations.CreateModel(
            name='VoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('DEBUG', 'Debug'), ('ERROR', 'Error'), ('WARNING', 'Warning')], max_length=20)),
                ('event', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='voice_agent.voiceconversation')),
            ],
            options={
                'db_table': 'voice_agent_log',
            },
        ),
        migrations.CreateModel(
            name='VoiceTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=10)),
                ('language', models.CharField(max_length=10)),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.9)),
                ('ai_response', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='voice_agent.voiceconversation')),
            ],
            options={
                'db_table': 'voice_agent_transcript',
            },
        ),
    ]
